# Site settings
title: My Hot Jekyll Site
email: austinpjohnson@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  My programming historian jekyll demo site. Thanks Amanda Visconti!
baseurl: "/jekylldemo" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: meDHieval
github_username:  apjmason

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
